export const THEMATIC_COMUNITY__CARDS = [
   {
     id: 0,
     src: "/sections/3d/chef.svg",
     metaAlt: "chef-hat",
     metaTitle: "chef-hat",
     title: "Кулинария",
     innerCommunities: [
       {
         id: 0,
         src: "/sections/3d/inner/draft1.png",
         metaAlt: "dog",
         metaTitle: "dog",
         title: "Дай лапу",
       },
       {
         id: 1,
         src: "/sections/3d/inner/draft2.png",
         metaAlt: "woman",
         metaTitle: "woman",
         title: "Пушистые лапки",
       },
       {
         id: 2,
         src: "/sections/3d/inner/draft3.png",
         metaAlt: "mask",
         metaTitle: "mask",
         title: "Мокрый нос",
       },
     ],
   },
   {
     id: 1,
     src: "/sections/3d/smile.svg",
     metaAlt: "smile",
     metaTitle: "smile",
     title: "Юмор",
     innerCommunities: [
       {
         id: 0,
         src: "/sections/3d/inner/draft1.png",
         metaAlt: "dog",
         metaTitle: "dog",
         title: "Дай лапу",
       },
       {
         id: 1,
         src: "/sections/3d/inner/draft2.png",
         metaAlt: "woman",
         metaTitle: "woman",
         title: "Пушистые лапки",
       },
       {
         id: 2,
         src: "/sections/3d/inner/draft3.png",
         metaAlt: "mask",
         metaTitle: "mask",
         title: "Мокрый нос",
       },
     ],
   },
   {
     id: 2,
     src: "/sections/3d/paw.svg",
     metaAlt: "paw",
     metaTitle: "paw",
     title: "Животные",
     innerCommunities: [
       {
         id: 0,
         src: "/sections/3d/inner/draft1.png",
         metaAlt: "dog",
         metaTitle: "dog",
         title: "Дай лапу",
       },
       {
         id: 1,
         src: "/sections/3d/inner/draft2.png",
         metaAlt: "woman",
         metaTitle: "woman",
         title: "Пушистые лапки",
       },
       {
         id: 2,
         src: "/sections/3d/inner/draft3.png",
         metaAlt: "mask",
         metaTitle: "mask",
         title: "Мокрый нос",
       },
     ],
   },
   {
     id: 3,
     src: "/sections/3d/aviasales.svg",
     metaAlt: "aviasales",
     metaTitle: "aviasales",
     title: "Путешествия",
     innerCommunities: [
       {
         id: 0,
         src: "/sections/3d/inner/draft1.png",
         metaAlt: "dog",
         metaTitle: "dog",
         title: "Дай лапу",
       },
       {
         id: 1,
         src: "/sections/3d/inner/draft2.png",
         metaAlt: "woman",
         metaTitle: "woman",
         title: "Пушистые лапки",
       },
       {
         id: 2,
         src: "/sections/3d/inner/draft3.png",
         metaAlt: "mask",
         metaTitle: "mask",
         title: "Мокрый нос",
       },
     ],
   },
   {
     id: 4,
     src: "/sections/3d/footbal.svg",
     metaAlt: "football",
     metaTitle: "football",
     title: "Спорт",
     innerCommunities: [
       {
         id: 0,
         src: "/sections/3d/inner/draft1.png",
         metaAlt: "dog",
         metaTitle: "dog",
         title: "Дай лапу",
       },
       {
         id: 1,
         src: "/sections/3d/inner/draft2.png",
         metaAlt: "woman",
         metaTitle: "woman",
         title: "Пушистые лапки",
       },
       {
         id: 2,
         src: "/sections/3d/inner/draft3.png",
         metaAlt: "mask",
         metaTitle: "mask",
         title: "Мокрый нос",
       },
     ],
   },
   {
     id: 5,
     src: "/sections/3d/heel.svg",
     metaAlt: "high-heels",
     metaTitle: "high-heels",
     title: "Для женщин",
     innerCommunities: [
       {
         id: 0,
         src: "/sections/3d/inner/draft1.png",
         metaAlt: "dog",
         metaTitle: "dog",
         title: "Дай лапу",
       },
       {
         id: 1,
         src: "/sections/3d/inner/draft2.png",
         metaAlt: "woman",
         metaTitle: "woman",
         title: "Пушистые лапки",
       },
       {
         id: 2,
         src: "/sections/3d/inner/draft3.png",
         metaAlt: "mask",
         metaTitle: "mask",
         title: "Мокрый нос",
       },
     ],
   },
   {
     id: 6,
     src: "/sections/3d/pen.svg",
     metaAlt: "pen",
     metaTitle: "pen",
     title: "Дизайн",
     innerCommunities: [
       {
         id: 0,
         src: "/sections/3d/inner/draft1.png",
         metaAlt: "dog",
         metaTitle: "dog",
         title: "Дай лапу",
       },
       {
         id: 1,
         src: "/sections/3d/inner/draft2.png",
         metaAlt: "woman",
         metaTitle: "woman",
         title: "Пушистые лапки",
       },
       {
         id: 2,
         src: "/sections/3d/inner/draft3.png",
         metaAlt: "mask",
         metaTitle: "mask",
         title: "Мокрый нос",
       },
     ],
   },
   {
     id: 7,
     src: "/sections/3d/brain.svg",
     metaAlt: "brain",
     metaTitle: "brain",
     title: "Познавательно",
     innerCommunities: [
       {
         id: 0,
         src: "/sections/3d/inner/draft1.png",
         metaAlt: "dog",
         metaTitle: "dog",
         title: "Дай лапу",
       },
       {
         id: 1,
         src: "/sections/3d/inner/draft2.png",
         metaAlt: "woman",
         metaTitle: "woman",
         title: "Пушистые лапки",
       },
       {
         id: 2,
         src: "/sections/3d/inner/draft3.png",
         metaAlt: "mask",
         metaTitle: "mask",
         title: "Мокрый нос",
       },
     ],
   },
   {
     id: 8,
     src: "/sections/3d/baby-carriage.svg",
     metaAlt: "baby-carriage",
     metaTitle: "baby-carriage",
     title: "Материнство",
     innerCommunities: [
       {
         id: 0,
         src: "/sections/3d/inner/draft1.png",
         metaAlt: "dog",
         metaTitle: "dog",
         title: "Дай лапу",
       },
       {
         id: 1,
         src: "/sections/3d/inner/draft2.png",
         metaAlt: "woman",
         metaTitle: "woman",
         title: "Пушистые лапки",
       },
       {
         id: 2,
         src: "/sections/3d/inner/draft3.png",
         metaAlt: "mask",
         metaTitle: "mask",
         title: "Мокрый нос",
       },
     ],
   },
 ];